version: '3.5'

services:
  bullboardz:
    container_name: bullboard
    image: deadly0/bull-board
    restart: always
    env:
      - REDIS_HOST: 172.27.10.137
      - REDIS_PORT: 6380
      - REDIS_DB: 13
    ports:
      - 3333:3000
    extra_hosts:
      - host.docker.internal:host-gateway