name: Continuous integration

on:
  push:
    branches: [dev, staging, serenity, halo, euphoria]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set environment variable
        run: |
          SHORT_SHA_COMMIT=$(git rev-parse --short HEAD)
          echo CONTAINER_RELEASE_IMAGE=ghcr.io/aura-nw/multisig-api:${GITHUB_REF_NAME}_${SHORT_SHA_COMMIT} >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ${{ env.CONTAINER_RELEASE_IMAGE }}
  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set environment variable
        run: |
          SHORT_SHA_COMMIT=$(git rev-parse --short HEAD)
          echo CONTAINER_RELEASE_IMAGE=ghcr.io/aura-nw/multisig-api:${GITHUB_REF_NAME}_${SHORT_SHA_COMMIT} >> $GITHUB_ENV
          echo REPO_MANIFEST_NAME=gitops >> $GITHUB_ENV
          echo REPO_MANIFEST_URL=github.com/aura-nw/gitops.git >> $GITHUB_ENV
          echo REPO_MANIFEST_BRANCH=main >> $GITHUB_ENV
          echo REPO_MANIFEST_ENV_DEV=./clusters/k8s-dev/multisig-safe >> $GITHUB_ENV
          echo REPO_MANIFEST_ENV_STAGING=./clusters/k8s-prod/multisig-safe >> $GITHUB_ENV
          echo REPO_MANIFEST_ENV_EUPHORIA=./clusters/k8s-testnet-euphoria/multisig-safe >> $GITHUB_ENV
          echo REPO_MANIFEST_ENV_SERENITY=./clusters/k8s-testnet-serenity/multisig-safe >> $GITHUB_ENV
          echo REPO_MANIFEST_TAG_IMAGE=image_multisig_api >> $GITHUB_ENV
      - name: Update manifest
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          chmod 777 -R ./ci
          ./ci/updateManifest.sh
